---
title: "Embedded Flipbook"
author: Me, an Rmarkdown writer and flipbook builder
output: html_document
---



```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F, error = F)
library(flipbookr)
library(tidyverse)
```


# A1. Here is some code (I'm naming the chunk "my_code"): 

You might think about setting this code chunk's option include = F, to hide the code and output.

```{r my_code, eval=F}
options(scipen = 10)
gapminder::gapminder %>% 
  filter(year == 1992) %>% 
  ggplot() + 
  theme_minimal() +
  theme(panel.background = element_rect(fill = "grey95")) + 
  theme(plot.background = element_rect(fill= "grey90")) +
  aes(x = gdpPercap) + 
  labs(x = "GDP per Capita, US$") +
  scale_x_log10() + 
  aes(y = lifeExp) + 
  labs(y = "Life Expectancy") + #BREAK
  theme(axis.title.y = element_text(colour = alpha("blue", 0))) +
  aes(size = pop) + 
  scale_size(range = c(1,8), trans = "sqrt", guide = F) +
  geom_blank() +
  geom_point(color = "white") +
  geom_point(alpha = .7, show.legend = F) + #BREAK
  aes(color = continent) + labs(color = NULL) #BREAK
```


```{r}
embed_flipbook(chunk_name = "my_code", 
               use_share_again = T,
               use_embed_xaringan = T,
               font_size = 120, 
               break_type = "user",
               display_type = "output",
               chunk_options = "fig.width = 6, fig.height = 4, out.width = '70%', fig.align = 'center'"
               )
```
