---
title: "ggplot layer dataframes"
subtitle: ""
author: "E. Reynolds"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    seal: FALSE
    nature:

      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse
background-image: url(https://images.unsplash.com/photo-1541781408260-3c61143b63d5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1500&q=80)
background-size: cover

# show layers w/ ggplot2::layer_data()

## Gina Reynolds



```{r, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = F, message = F, warning = F, cache = T)
library(flipbookr)
```

---





```{r stats, fig.show='hide'}
g <- mtcars %>% ggplot() +
  aes(x = cyl) +
  aes(y = wt) +
  stat_summary(geom = "pointrange",
               fun.data = mean_se) +
  geom_blank() +
  geom_point(alpha = .3) +
  geom_point(aes(color = "blue")) + 
  geom_boxplot(alpha = .2) +
  geom_boxplot(alpha = .4,
               color = "green",
               aes(group = cyl)) +
  geom_boxplot(alpha = .4,
               aes(color = cyl)) +
  geom_vline(xintercept = 5) +
  geom_vline(aes(xintercept = mean(cyl)),
             color = "plum") +
  stat_summary(geom = "point",
               color = "goldenrod2", 
               size = 8,
               fun = "mean")
```

`r chunk_reveal("stats", left_assign = T, title = "### ggplot plotting layers")`

---

### a function for showing last layer data frame

```{r, echo = T}
last_layer_data <- function(plot){
  
  layer_data(plot, ifelse(length(plot$layers) >= 1, 
                          length(plot$layers), 1))
  
}
```

---


`r chunk_reveal("stats", left_assign = T, left_assign_add = "# inspect data of most recent layer\nlast_layer_data()", widths = c(1, 2), title = "### ... dataframes computed for layers")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
