---
title: Overlapping conditional proportions protocol 
---


```{r, include = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(tidyverse)
```

### {.tabset .tabset-fade .tabset-pills}


#### 1. Data manipulation


Do data cleaning, create variables, and then subsetting according to the categories of interest

```{r data_manipulation, echo = F}
Titanic %>% 
  as.data.frame() %>% 
  uncount(weights = Freq) %>% 
  mutate(child_or_female = 
           Age == "Child"| 
           Sex == "Female" ) ->
all_data

all_data %>% 
  filter(Age == "Child") ->
child_data

all_data %>% 
  filter(Sex == "Female") ->
female_data

all_data %>% 
  filter(child_or_female) ->
child_or_female_data
```


```{r}
flipbookr::embed_flipbook(chunk_name = "data_manipulation",
                          use_share_again = T,
                          use_embed_xaringan = T)
```

#### 2. Combine subsets and calculate percentages

Combine subsets of the data, recording the subset in a variable, and calculate percentages

```{r a_table, echo = F}
bind_rows(all_data %>% 
            mutate(which_subset = "all"),
          child_data %>% 
            mutate(which_subset = "child"),
          female_data %>% 
            mutate(which_subset = "female"),
          child_or_female_data %>% 
            mutate(which_subset = 
                     "child_or_female")) %>%
  mutate(which_subset = 
           fct_inorder(which_subset)) ->
bound_rows
  
bound_rows %>%   
  group_by(which_subset, Survived) %>%  # here 3 different outcomes, maybe doing some na subset
  count() %>% 
  group_by(which_subset) %>% 
  mutate(percent = (100*n/sum(n)) %>% 
           round(1)) ->
my_table; my_table
```


```{r}
flipbookr::embed_flipbook(chunk_name = "a_table",
                          use_share_again = T,
                          use_embed_xaringan = T,
                          widths = c(1.2, 1))
```



#### 3. Viz of course

```{r a_plot, echo = F}
my_table %>% 
  ggplot() +
  aes(x = which_subset) +
  aes(y = percent) +
  geom_col(alpha = .5,
           color = "grey") +
  aes(fill = Survived) +
  scale_fill_manual(values = c("oldlace", "plum")) +
  geom_text(aes(label = 
                  paste0(percent, 
                         "%","\ncount:", 
                         n),
                alpha = Survived),
            y = 3,
            vjust = 0,
            lineheight = .7, show.legend = F) +
  scale_y_continuous(limits = c(0,100)) +
  theme_minimal() 
```


```{r}
flipbookr::embed_flipbook(chunk_name = "a_plot",
                          use_share_again = T,
                          use_embed_xaringan = T)
```

