---
title: "checker"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
LETTERS[1:25] %>% 
  tibble(unit = .) %>% 
  mutate(rank = (1:n())-1) %>% 
  ggplot() +
  aes(x = rank %% 5) +
  aes(y = -(rank %/% 5)) +
  geom_label(aes(label = unit),
             alpha = .3) +
  aes(fill = rank %% 2) +
  aes(fill = as.character(rank %% 2)) +
  geom_tile() +
  coord_equal() +
  theme_void() +
  theme(legend.position = "none") +
  theme(plot.background = element_rect(fill = "grey75")) +
  scale_fill_manual(values = c("beige", "plum3"))
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

