---
title: "positions"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(tidyverse)
set.seed(98789)
n <- 22
tibble(type = sample(LETTERS[1:3], n, replace = T),
       state = sample(state.abb[1:4], n, replace = T),
       event_occurs = sample(c("Yes", "No"), n, replace = T)) %>% 
  ggplot() +
  ggthemes::theme_igray() +
  geom_bar(position = "dodge2") + #ROTATE
  geom_bar(position = "identity") + #ROTATE
  geom_bar(position = "fill") + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single")) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single", padding = .2)) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single", reverse = T)) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "total", reverse = T)) + #ROTATE
  geom_bar(position = position_dodge(preserve = "single")) + #ROTATE
  geom_bar(position = position_dodge(width = 0.6)) + #ROTATE
  geom_bar(position = "stack") + #ROTATE
  geom_bar(position = "dodge") + #ROTATE
  aes(fill = factor(event_occurs)) + 
  theme(legend.position = "top") +
  theme(legend.justification = 0) +
  scale_fill_manual(values = c("plum4", "goldenrod1") ) + 
  aes(x = type) + 
  facet_grid(state~.) + 
  scale_y_continuous(expand = expansion(mult = c(.025, .3))) 
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "rotate", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

