---
title: "embedded_flipbooks/code and titanic"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(tidyverse)
Titanic %>% 
  as.data.frame() %>% 
  uncount(weights = Freq) %>% 
  ggplot() +
  ggthemes::theme_igray() +
  aes(x = 1) + labs(x = NULL) + theme(axis.text.x = element_blank()) +
  geom_bar(position = 
             position_dodge2(preserve = "single")) +
  stat_count(geom = "text",
             aes(label = after_stat(count), 
                 y = after_stat(count) + 65),
             vjust = 0,
             size = 4,
             position = 
               position_dodge2(width = .9,
                               preserve = "single")) + #BREAK
  aes(fill = Survived) + 
  theme(legend.position = "top") +
  theme(legend.justification = 0) +
  scale_fill_viridis_d(option = "inferno") + #BREAK
  aes(x = Sex) + theme(axis.text.x = element_text()) + #BREAK
  facet_grid(Class~.) + 
  scale_y_continuous(expand = expansion(mult = c(.025, .3))) + #BREAK
  facet_grid(Class~Age) #BREAK
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

