---
title: "waldo"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = TRUE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
set.seed(12456)
num <- 10
tibble(type = sample(LETTERS[1:2], num, replace = T) ,
       state = sample(state.abb[1:3], num, replace = T) ,
       event_occurs = sample(c("Yes", "No"), num, replace = T) %>% 
         factor()) %>% 
  count(type, state, event_occurs,.drop = F) %>% 
  ggplot() + 
  aes(x = type, y = n, fill = event_occurs) +
  facet_grid(state~.) +
  geom_col(position = "dodge", 
           width = 0.7,
           color = "grey35") +
  geom_text(aes(label = n), 
            position = position_dodge(width = .7), 
            vjust = -0.5) +
  scale_y_continuous(limits = c(0,4))
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 100%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

